wix-ui-icons-common docs
wix/wix-ui pull request #1907
Opened 2020-08-24 13:13 UTC by gendeld

2020-08-24 13:25 UTC, shlomitc reviewed
I know it's still a WIP, just pointing out several small issues I saw

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/.storybook/stories.scss
> +body {
remove

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/.storybook/preview-head.html
> +<!-- Old Helvetica Neue font -->
can keep only helvetica

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/wix-ui-icons-common.code-workspace
> +{
remove

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/src/index.story.st.css
> +div[data-hook="icon-list"] h2 {
If it's a change that should be done as part of the `wix-storybook-utils`, let's do it there.
same for the second hack

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/src/index.story.js
> +  storyName: "1.4 Component Icons",
That's probably relevant in WSR and not here

2020-08-24 13:25 UTC, shlomitc commented on packages/wix-ui-icons-common/src/index.story.js
> +        "https://github.com/wix/wix-style-react/tree/master/src/MessageModalLayout/",
fix it

2020-08-25 13:20 UTC, gendeld commented on packages/wix-ui-icons-common/src/index.story.st.css
> +div[data-hook="icon-list"] h2 {
The stories are kind of mixed on the issue
![image](https://user-images.githubusercontent.com/4023882/91179171-d3e7a500-e6ee-11ea-8f80-a898ac0445af.png)
![image](https://user-images.githubusercontent.com/4023882/91179137-c7fbe300-e6ee-11ea-95fb-4a7f37b0a7a6.png)
![image](https://user-images.githubusercontent.com/4023882/91179156-cdf1c400-e6ee-11ea-81c5-1b9c2b63a839.png)

2020-08-25 13:34 UTC, gendeld commented on packages/wix-ui-icons-common/src/index.story.st.css
> +div[data-hook="icon-list"] h2 {
![image](https://user-images.githubusercontent.com/4023882/91180706-ae5b9b00-e6f0-11ea-8e42-23f574077a76.png)
![image](https://user-images.githubusercontent.com/4023882/91180718-b3204f00-e6f0-11ea-850b-1da94c0de982.png)
In the Zeplin,
it changes from story to story, I've seen 18px, 24px, 30px, 54px, 60px

2020-08-31 07:15 UTC, shlomitc commented on packages/wix-ui-icons-common/src/test/allicons.e2e.ts
> +  eyes.it(`check icons - All`, async () => {
does it take a screenshot of all scrollable content?

2020-08-31 07:15 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/CategoryTable.tsx
> +  debugger;
remove

2020-08-31 07:15 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/index.story.js
> +      a: () => {},
is this needed?

2020-08-31 07:15 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/types.ts
> +export type OmitPolyfill<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
we can consider also upgrading the typescript version which already contains `Omit`

2020-09-03 07:40 UTC, shlomitc requested changes

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/CategoryTable.tsx
> +  return require(`../../src/system/dist/components/${name}`).default;
1. isn't there an index file instead of manually requiring each?
2. is this dynamically loading the icons? how does it affect the bundle?

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/icons/system.ts
> +import { Icon } from "../types";
I wonder if those files should sit in the `src` instead of the stories.
it's kind of a meta-data per icon so maybe it should sit close to it and not specifically to the docs.

wdyt?

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.tsx
> +    <div data-hook="icons-list">
1. reusable components' `data-hook`s should always be provided as a prop - `<CategoryList dataHook="icons-list"/>`

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/package.json
> +    "react": "^16.0.0",
should be a `~` on the relevant React version

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/package.json
> +    "typescript": "^4.0.2",
just making sure - the d.ts of ts@4 are fully compatible with ts@3 versions? our consumers are probably using the older

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/utils.tsx
> +  for (const { category = "Other", ...icon } of icons) {
Should there actually be any `Other`? icons without a category sound like a mistake

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/CategoryTable.tsx
> +import React from "react";
there's a bit of a mess here.
1. This component is mixing UI elements from `wix-storybook-utils`. Is that temporary? The plan will be ditching those?
2. This component becomes a "smart" component since it's actually doing the import logic - we usually try to split the concerns. UI components are responsible to display, while the logic is higher in the tree hierarchy and only the data is passed as a prop (a - gather the data, b - pass it to the UI)
3. once the component is UI-only, then it probably means you can drop one of them. currently, there are two - one for the system and one for the general. I think that there should only be one, no?

2020-09-03 07:40 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/general/index.story.js
> +import React, { useState, useMemo, useEffect } from "react";
unused `use`s

2020-09-03 08:46 UTC, gendeld commented on packages/wix-ui-icons-common/stories/icons/system.ts
> +    category: undefined,
I want to put in undefined to denote that we might want to change it in the future

2020-09-03 08:49 UTC, gendeld commented on packages/wix-ui-icons-common/stories/utils.tsx
> +  for (const { category = "Other", ...icon } of icons) {
All system icons are uncategorized at the moment, though that might change sometime in the future

2020-09-03 14:48 UTC, shlomitc requested changes

2020-09-03 14:48 UTC, shlomitc commented on packages/wix-ui-icons-common/src/general/raw/Attachment.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
All these icons don't seem relevant for this PR, let's split it

2020-09-03 14:48 UTC, shlomitc commented on packages/wix-ui-icons-common/src/general/raw/ChevronLeftLargeSmall.svg
> +  <g fill="none" fill-rule="evenodd">
please follow the icons guidelines: https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common#guidelines

2020-09-03 14:48 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/utils.tsx
> +  for (const { category = "Other", ...icon } of icons) {
Consider calling it "uncategorized" instead.

2020-09-06 08:06 UTC, shlomitc requested changes

2020-09-06 08:06 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/index.story.js
> +  return [title, <Sizes sizes={iconDescriptors} />, description];
refactor `<Sizes/>` component out.
the output should be raw data - component should appear only in the last stage in the `<CategoryList/>` itself

2020-09-06 08:06 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/index.story.js
> +const mapIconToRow = ({ title, sizes, description }) => {
what's the signature of this function?

2020-09-06 11:39 UTC, gendeld commented on packages/wix-ui-icons-common/package.json
> +    "typescript": "^4.0.2",
The type definitions and generators of the dist icons themselves have not changed.

2020-09-06 12:51 UTC, gendeld commented on packages/wix-ui-icons-common/stories/system/index.story.js
> +const mapIconToRow = ({ title, sizes, description }) => {
Receives icon metadata and returns row (React Node array)

2020-09-06 13:38 UTC, shlomitc requested changes

2020-09-06 13:38 UTC, shlomitc commented on packages/wix-ui-icons-common/package.json
> +    "@stylable/runtime": "^3.8.4",
not sure why this is needed

2020-09-06 13:38 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/index.story.js
> +const mapIconToRow = ({ title, sizes, description }) => {
oh, I thought this is already a `tsx` file. I think it should be anyway

2020-09-06 14:19 UTC, gendeld commented on packages/wix-ui-icons-common/package.json
> +    "@stylable/runtime": "^3.8.4",
src/globals.d.ts depends on the types declared there.
CI doesn't pass without it.

2020-09-08 17:24 UTC, shlomitc approved these changes
overall code looks awesome. styling and the rest of the features can be done in the next PRs 👍

2020-09-08 17:24 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/system/index.story.tsx
> +        "https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common",
you can also point to the `system` folder of the icons

2020-09-13 07:08 UTC, shlomitc submitted a review, later dismissed

2020-09-13 07:56 UTC, merged