<Popover/> - fix clickOutside for nested popovers
wix/wix-ui pull request #1917
Opened 2020-09-09 15:26 UTC by EgoziE

Currently there's an issue, clicking inside a **nested portaled** popover is considered a "clicked outside" the outer popover.
I created a "popover context" in order to let a **nested portaled** popover know when a parent of his is clicked.

I also created a complicated story to test it:
![image](https://user-images.githubusercontent.com/35173937/92618530-22896780-f2c9-11ea-9913-c636b325ba48.png)

```
<Popover
  appendTo="window"
  shown
  onClickOutside={() => console.log('Outside 2')}
  showArrow
  placement="top"
  excludeClass="excludeClass"
>
  <Popover.Element>
    <div style={{ height: '150px', width: '150px', background: 'lightgreen' }}>
      1
    </div>
  </Popover.Element>
  <Popover.Content>
    <div style={{ height: '120px', width: '120px', background: 'lightgreen' }}>
      <Popover
        appendTo="window"
        shown
        onClickOutside={() => console.log('Outside 3')}
        showArrow
        placement="top"
      >
        <Popover.Element>
          <div
            style={{
              height: '120px',
              width: '120px',
              background: 'lightgreen',
            }}
          >
            2
          </div>
        </Popover.Element>
        <Popover.Content>
          <div
            style={{ height: '90px', width: '90px', background: 'lightgreen' }}
          >
            <Popover
              appendTo="window"
              shown
              onClickOutside={() => console.log('Outside 4')}
              showArrow
              placement="top"
            >
              <Popover.Element>
                <div
                  style={{
                    height: '90px',
                    width: '90px',
                    background: 'lightgreen',
                  }}
                >
                  3
                </div>
              </Popover.Element>
              <Popover.Content>
          <div
            style={{ height: '70px', width: '70px', background: 'lightgreen' }}
          >
            <Popover
              appendTo="window"
              shown
              onClickOutside={() => console.log('Outside 5')}
              showArrow
              placement="top"
            >
              <Popover.Element>
                <div
                  style={{
                    height: '70px',
                    width: '70px',
                    background: 'lightgreen',
                  }}
                >
                  4
                </div>
              </Popover.Element>
              <Popover.Content>
                <div
                  style={{
                    height: '40px',
                    width: '40px',
                    background: 'lightgreen',
                  }}
                >
                  5
                </div>
              </Popover.Content>
            </Popover>
          </div>
              </Popover.Content>
            </Popover>
          </div>
        </Popover.Content>
      </Popover>
    </div>
  </Popover.Content>
</Popover>
```

2020-09-10 07:34 UTC, argshook commented
imo the story you created can be committed under `Tests` category

2020-09-10 08:46 UTC, argshook commented
i got a bit confused by the example, but only because of what's console.logg'ed.

<details>
<summary>
  This was more clear for me. The big change is numbering in `console.log('Outside #')`, that's all
</summary>

```
<Popover
  appendTo="window"
  shown
  onClickOutside={() => console.log('Outside 1')}
  showArrow
  placement="top"
  excludeClass="excludeClass"
>
  <Popover.Element>
    <div style={{ height: '150px', width: '150px', background: 'lightgreen' }}>
      1
    </div>
  </Popover.Element>
  <Popover.Content>
    <div style={{ height: '120px', width: '120px', background: 'lightgreen' }}>
      <Popover
        appendTo="window"
        shown
        onClickOutside={() => console.log('Outside 2')}
        showArrow
        placement="top"
      >
        <Popover.Element>
          <div
            style={{
              height: '120px',
              width: '120px',
              background: 'lightgreen',
            }}
          >
            2
          </div>
        </Popover.Element>
        <Popover.Content>
          <div
            style={{ height: '90px', width: '90px', background: 'lightgreen' }}
          >
            <Popover
              appendTo="window"
              shown
              onClickOutside={() => console.log('Outside 3')}
              showArrow
              placement="top"
            >
              <Popover.Element>
                <div
                  style={{
                    height: '90px',
                    width: '90px',
                    background: 'lightgreen',
                  }}
                >
                  3
                </div>
              </Popover.Element>
              <Popover.Content>
                <div
                  style={{
                    height: '70px',
                    width: '70px',
                    background: 'lightgreen',
                  }}
                >
                  <Popover
                    appendTo="window"
                    shown
                    onClickOutside={() => console.log('Outside 4')}
                    showArrow
                    placement="top"
                  >
                    <Popover.Element>
                      <div
                        style={{
                          height: '70px',
                          width: '70px',
                          background: 'lightgreen',
                        }}
                      >
                        4
                      </div>
                    </Popover.Element>
                    <Popover.Content>
                      <div
                        style={{
                          height: '40px',
                          width: '40px',
                          background: 'lightgreen',
                        }}
                      >
                        5
                      </div>
                    </Popover.Content>
                  </Popover>
                </div>
              </Popover.Content>
            </Popover>
          </div>
        </Popover.Content>
      </Popover>
    </div>
  </Popover.Content>
</Popover>
```
</details>

2020-09-10 08:47 UTC, argshook approved these changes
awesome work :+1:

2020-09-13 13:58 UTC, shlomitc requested changes

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/tooltip/Tooltip.spec.tsx
> +    document.body.innerHTML = '';
this doesn't necessarily mean that the dom is clean. there could be some async operations that are still hanging

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/click-outside/ClickOutside.tsx
> +            .some(c => excludeClass.split(' ').includes(c)))
`excludeClass.split(' ')` can be done once in the function instead of in the `some` loop.

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/PopoverContext.tsx
> +  excludeClass: string;
consider giving it a more descriptive name that explains the intent. Also, I think that this must have some explanation next to it.

also, since it's anyway gonna be multiple, simply pass it as an array, it's gonna be easier to `[].concat()` instead of doing string manipulation

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +describe('Click outside nested popovers', () => {
I think that it's better if all tests will sit in the same file, otherwise, it breaks the convention.
For example, the `sync` and `async` tests are missing here, also there's no usage of the driver methods at all

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +    act(() => {
why is `act` needed?

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +    expect(level4).toHaveBeenCalledTimes(4);
I think this worth splitting to a separate `spec` since this is the case that you actually click outside

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +    expect(level4).toHaveBeenCalledTimes(3);
I think it's enough to keep only this last assertion of `level-1`. all the rest are just duplications.

Also, you can simply create two levels, the others are also redundant

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +  it('should click outside a nested popover', () => {
the test name should describe the outcome and not what it is doing.
test 1 - it should close all nested popovers when clicking outside
test 2 - it should not close any popover when clicking on the deepest popover
etc...

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/Popover.tsx
> +
I'd change it that `ClickOutside` can take an array of strings and do this concatenation instead of each consumer  of it will do it separately

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/click-outside/ClickOutside.tsx
> +            .some(c => excludeClass.split(' ').includes(c)))
this might not be needed if getting `excludeClass` as an array

2020-09-13 13:58 UTC, shlomitc commented on packages/wix-ui-core/src/components/popover/Popover.tsx
> +              {context => {
```suggestion
              {({excludeClass}) => {
```

2020-09-13 14:03 UTC, EgoziE commented on packages/wix-ui-core/src/components/click-outside/ClickOutside.tsx
> +            .some(c => excludeClass.split(' ').includes(c)))
I didn't want to break API.
excludeClass was easily converted from a single class to a list of classes.

But I see your point, I'll refactor the loop.

2020-09-13 15:56 UTC, EgoziE commented on packages/wix-ui-core/src/components/popover/tests/PopoverNestedTest.spec.tsx
> +describe('Click outside nested popovers', () => {
I prefer to leave it in a separate file, it's inside the `test` folder, so chances for missing it are low

2020-09-14 07:08 UTC, merged