[Draft 2][wix-ui-icons-common] Add icon search to storybook
wix/wix-ui pull request #1932
Opened 2020-09-17 16:33 UTC by gendeld

2020-09-21 07:25 UTC, shlomitc requested changes
Excellent job 👍
I think that's much more clear than the previous draft.
It's really easy to follow and understand, also code is structured nicely.
just a few comments

2020-09-21 07:25 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/search-input/SearchInput.tsx
> +import React, { ChangeEvent } from "react";
Technically component this should go to `wix-storybook-utils` since it's a UI element.
The only thing that could stay here is the css layout of it (putting it in the right place, fixating the width, etc...)

2020-09-21 07:25 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.spec.tsx
> +};
this should go into the driver

2020-09-21 07:25 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.spec.tsx
> +    expect(driver.getCategoryRows()).toHaveLength(1);
I think it will be stronger to also make sure you get the correctly filtered value, instead of just checking that one row appears

2020-09-21 07:25 UTC, shlomitc commented on packages/wix-ui-icons-common/tsconfig.json
> +    "esModuleInterop": true
just make sure the output of the icons is not changed

2020-09-21 07:25 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +export default class CategoryListDriver {
We usually prefer creating drivers that are stateless (simple functions).

2020-09-21 08:23 UTC, gendeld commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +export default class CategoryListDriver {
It's not stateful 🤔
The class syntax just makes it easier in this context to use methods within methods given the this keyword.
Otherwise I'd need to define the functions and then return them.
More of a stylistic thing, should I change it to a function anyway?

2020-09-21 08:52 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +  getCategoryTitles = () =>
We prefer returning primitives instead of elements. In the `unidriver` world, we don't want consumers to interact with the internal elements.

read more here: https://github.com/wix/wix-style-react/blob/master/docs/contribution/TEST_DRIVERS_GUIDELINES.md#drivers-apis

so my suggestion is to return `getAmountOfCategoryTitles()`

2020-09-21 08:52 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +  getSearchInput = () =>
This is internal, so no need to expose it as a class method

2020-09-21 08:52 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +export default class CategoryListDriver {
in our libraries, we do return an object of functions.
In this case, I agree that it's just a matter of style since this driver is not exposed to consumers, so you can keep it that way

2020-09-21 08:52 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/category-list/CategoryList.driver.tsx
> +    await waitForDomChange();
This is a deprecated method, you should use `waitFor` instad
https://testing-library.com/docs/dom-testing-library/api-async#waitfor

2020-09-21 09:27 UTC, gendeld commented on packages/wix-ui-icons-common/stories/components/search-input/SearchInput.tsx
> +import React, { ChangeEvent } from "react";
https://github.com/wix/wix-ui/pull/1935

2020-09-21 10:11 UTC, gendeld commented on packages/wix-ui-icons-common/tsconfig.json
> +    "esModuleInterop": true
Good catch 😅

2020-09-22 14:43 UTC, shlomitc approved these changes

2020-09-22 15:30 UTC, merged