Updating ChatDisabled and adding new icons
wix/wix-ui pull request #1972
Opened 2020-11-24 14:16 UTC by ZilvinasMaciulis

2020-11-25 09:00 UTC, TalZa1810 requested changes
Hi @ZilvinasMaciulis 
I've added few comments.
Also, if the icons [here](https://github.com/wix/wix-ui/pull/1973) related to this PR, please update this PR instead of creating a new one.

2020-11-25 10:46 UTC, roibWix commented on packages/wix-ui-icons-common/src/general/raw/Microphone.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
added in another commit

2020-11-25 17:36 UTC, gendeld commented
packages/wix-ui-icons-common/src/general/raw/ViedeoCameraDisabled.svg
Wrong icon name

2020-11-25 17:38 UTC, gendeld requested changes
packages/wix-ui-icons-common/src/general/raw/ViedeoCameraDisabled.svg
Wrong icon name

2020-11-30 09:02 UTC, gendeld approved these changes

2020-11-30 09:02 UTC, merged