Dropdown keyboard Accessibility - open with space key
wix/wix-ui pull request #2077
Opened 2021-04-15 10:44 UTC by aarnoldaas

We got request from @NeilWix to improve dropdown accessibility - open dropdown options with space key

2021-04-18 06:48 UTC, sivanharel commented
@aarnoldaas - Thanks for the contribution!

The builds are failed since your commit is not signed.
In order to contribute to the library, you need to first sign your commits. If you haven’t set-up your GitHub account for signed commits, please follow this guide: https://github.com/wix/wix-style-react/blob/master/packages/wix-style-react/docs/contribution/CREATE_PR.md#sign-commits

2021-04-18 06:52 UTC, sivanharel commented on packages/wix-ui-core/src/components/dropdown/Dropdown.tsx
> +        case ' ': {
Enter key is also closing the list. Should the `space` also close the dropdown list or only open it?

2021-04-18 08:20 UTC, NeilWix commented on packages/wix-ui-core/src/components/dropdown/Dropdown.tsx
> +        case ' ': {
both enter and space keys should toggle (expand, collapse) the options menu

2021-04-18 13:19 UTC, sivanharel commented on packages/wix-ui-core/src/components/dropdown/Dropdown.tsx
> +        case ' ': {
Thanks @NeilWix!
@aarnoldaas please add this functionality as well 🙏

2021-04-19 07:37 UTC, aarnoldaas commented on packages/wix-ui-core/src/components/dropdown/Dropdown.tsx
> +        case ' ': {
Clicking spacekey trigger poppover onClick method, I just need to mark space as closing key so it will not trigger open/close multiple times.

2021-04-19 08:13 UTC, sivanharel requested changes
Now the `space` key opens and closes the list but doesn't select the new option.
You should also keep the `case ' ':` and then it would work as expected :)

2021-04-19 08:15 UTC, sivanharel commented
You could test it on the storybook playground tab :)

2021-04-19 08:31 UTC, aarnoldaas commented
@NeilWix should space key select option or just toggle the dropdown?

2021-04-19 13:46 UTC, aarnoldaas commented
Checked how native Select works. It selects option with space key. Made it to work same way.

2021-04-19 13:50 UTC, sivanharel approved these changes
In ord

2021-04-19 14:17 UTC, merged