[wix-storybook-utils] Introduce global loader config for playground components
wix/wix-ui pull request #2078
Opened 2021-04-18 17:20 UTC by mykas

This PR is part of improved stories effort. This will introduce global configuration to get playground components loaded for every code section. 

You will only need to introduce path to the file which imports all components and loader will add it to every story file to be loaded.

2021-04-18 17:23 UTC, mykas commented on packages/wix-storybook-utils/src/loader/index.js
> -const prepareStory = require('react-autodocs-utils/src/prepare-story'); // TODO: should be part of wix-storybook-utils
@argshook I am making this comment to actual realisation. For now I just moved `prepareStory` function near here with specific improvements for playground components, but I would like to improve it more by getting rid of `storiesOf` function etc. So my next PR will be about this.

2021-04-18 17:26 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
@shlomitc @EgoziE @jonathanadler what do you think about this? Does this name make sense to you? 

What it would mean is that we will able to add this path to webpack config for storybook loader and forget about it.

2021-04-18 18:13 UTC, mykas commented on packages/wix-storybook-utils/src/loader/index.js
> -const prepareStory = require('react-autodocs-utils/src/prepare-story'); // TODO: should be part of wix-storybook-utils
Fun fact: I was thinking now what would Arijus say in this PR when checking the code. 

Guess what! No tests! So of course tests will be moved here too from react-autodos-utils and updated with changes that got introduced for playground components.

2021-04-19 07:11 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
I think we should have a single configuration file to point at that the loader will read from.
In this file, you will define the components scope

2021-04-19 07:27 UTC, jonathanadler commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
Awesome!
A single config file would be a nice approach 👌

2021-04-19 07:28 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
But what does it mean a single file? Do you mean moving all these params to one file and then in this webpack config reference it?

2021-04-19 07:29 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
Or you mean that loader will expect certain file to be in the same folder and try to read it?

2021-04-19 07:33 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
```js
/* .storybook/wsu.config.js */
module.exports = {
  playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
}
```

or maybe you can already import the `allComponents` file in the config file

2021-04-19 07:43 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory.js
> +      });
```suggestion
      if (isES5) {
        // add requires
        ast.program.body.unshift(parse('const { storiesOf } = require("@storybook/react")'));
        ast.program.body.unshift(parse('const story = require("wix-storybook-utils/Story").default'));
      } else {
        // add imports
        ast.program.body.unshift(parse('import { storiesOf } from "@storybook/react"'));
        ast.program.body.unshift(parse('import story from "wix-storybook-utils/Story"'));
      }

      return ast;
    })
    .then(ast => {
      // TODO: this is not too good, unfortunatelly, i cant return
      // rejected promise from within visitor, babylon complains
      let error = null;

      const configAST = parse(`(${JSON.stringify(storyConfig)})`);
      let configProperties;

      visit(configAST)({
        ObjectExpression(path) {
          const storiesOfProperty = types.objectProperty(types.identifier('storiesOf'), types.identifier('storiesOf'));
          path.node.properties.push(storiesOfProperty);

          if (storyConfig.playgroundComponentsPath) {
            const playgroundComponentsProperty = types.objectProperty(
              types.identifier('playgroundComponents'),
              parse(`require("${path.relative(sourcePath, storyConfig.playgroundComponentsPath)}")`)
            );

            path.node.properties.push(playgroundComponentsProperty);
          }

          configProperties = path.node.properties;
          path.stop();
        },
      });
```

2021-04-19 07:43 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory.js
> +      });
github shows a big diff, but the idea is not big: don't do `import`/`require` at the top, do one `require` right into the `storyConfig`

2021-04-19 07:43 UTC, argshook commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
not sure we need to aim at this. storybook anyway needs a `webpack.config.js` which is where we keep `wix-storybook-utils` config.

if we extract the config of `wix-storybook-utils` from `webpack.config.js` to a separate file, we'll need to deal with at least two config files instead of one, which is opposite of what this comment thread is about?

2021-04-19 07:44 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
I did some research on importing files already to webpack config and its problematic due the way webpack works only with common js. For now passing a path is one way we can approach this.

2021-04-19 07:45 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
And about your example: do you expect it to be loaded inside webpack.config.js or you expect webpack to try to find such file?

2021-04-19 07:47 UTC, mykas commented on packages/wix-storybook-utils/src/loader/prepareStory.js
> +      });
oh thats nice 🤔

2021-04-19 07:53 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
I'm ok with keeping it in the `webpack.config.js` file.
The default value of `playgroundComponentsPath` here should point to the `index.js` file which makes sense to have in every project

2021-04-19 09:01 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
Are we sure we want default value? We have different patterns across libraries too. 
tpa: src/components
wsr: src/
wuc: src/components

2021-04-19 09:20 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
`src/index` is the most common in libraries, but you can try to resolve both paths

2021-04-19 09:22 UTC, mykas commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
one more thing. Its not just about component but also icons. We would need to have the file anyway to import icons. Or we want to assume icons and load them for every lib?

2021-04-19 09:30 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/webpack.config.js
> +        playgroundComponentsPath: path.resolve(__dirname, '..', 'src', 'allComponents'),
So looks like we must have a separate entry file for the playground context. Let’s just find a better name than the allComponents and not place it in src since it shouldn’t go to dist

2021-04-19 10:33 UTC, mykas commented on packages/wix-storybook-utils/.storybook/playground.scope.js
> +import * as Icons from 'wix-ui-icons-common';
@shlomitc what do you think? `playground.scope.js` ? any other name you have in mind?

2021-04-19 10:33 UTC, mykas commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.spec.js
> +/* global describe it expect */
@argshook all hail to unit tests!

2021-04-19 10:55 UTC, argshook requested changes

2021-04-19 10:55 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.js
> +            storyConfig.playgroundComponentsPath && path.node.properties.push(playgroundComponentsProperty);
```suggestion
            path.node.properties.push(playgroundComponentsProperty);
```

2021-04-19 10:55 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.js
> +            const playgroundComponentsProperty = types.objectProperty(types.identifier('playgroundComponents'), types.identifier(`require('${playgroundComponentsPath}').default`));
```suggestion
            const playgroundComponentsProperty = types.objectProperty(types.identifier('playgroundComponents'), parse(`require('${playgroundComponentsPath}').default`));
```

the value of a property is not an identifier, it's a function call. an easy way to get ast of that is to use `parse`

2021-04-19 10:55 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.spec.js
> +        playgroundComponentsPath: '/file'
`/file` would be a `file` in the root of a filesystem, that's not what we want. let's try to imitate a more realistic scenario.
```suggestion
        playgroundComponentsPath: 'playground.scope.js'
```

`playgroundComponentsPath` should probably expect a path which is relative to `.storybook/webpack.config.js`

2021-04-19 10:55 UTC, argshook commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.spec.js
> +      return expect(prepareStory(config, '/kazkas/kazkas')(source)).resolves.toEqual(expectation);
maybe there's a way to have a more realistic test? it's not very clear how `/kazkas/kazkas` becomes `../../`, especially when `playgroundComponentsPath` points to `/file` - a file on root

also let's use english :)
```suggestion
      return expect(prepareStory(config, '/something/something')(source)).resolves.toEqual(expectation);
```

2021-04-19 10:58 UTC, mykas commented on packages/wix-storybook-utils/src/loader/prepareStory/prepareStory.spec.js
> +      return expect(prepareStory(config, '/kazkas/kazkas')(source)).resolves.toEqual(expectation);
oh no, I left lithuanian! its our secret language! how dare me

2021-04-19 11:11 UTC, shlomitc commented on packages/wix-storybook-utils/.storybook/playground.scope.js
> +import * as Icons from 'wix-ui-icons-common';
`playgroundScope.js` could be enough. not sure we need the mid-name of `.scope` since it's not a repeating convention in the same library

2021-04-19 14:23 UTC, merged