New media icons and updated list of icons from sketch
wix/wix-ui pull request #2101
Opened 2021-05-05 09:25 UTC by Zohar-Telor

Uploaded new icons and updated the list in SB

2021-05-06 19:32 UTC, shlomitc requested changes
Did a very quick review. Might be more when I’m in front of my computer

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/DismissBold.svg
> +    <path id="dismissbold-a" d="M13.4135707,12.0003772 L16.7066965,8.70752558 C17.0977678,8.31729149 17.0977678,7.68366398 16.7066965,7.29342989 C16.3166408,6.90219004 15.6838162,6.90219004 15.292744
This looks incorrect. Should not have defs

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/ShapeCropBold.svg
> +    <path id="shapecrop-a" d="M13.5,18.5 C11.269,18.5 9.396,17.021 8.755,15 L10.136,15 L8.513,13.377 C8.523,12.953 8.597,12.548 8.707,12.156 L11.55,15 L12.965,15 L9.114,11.149 C9.276,10.848 9.467,10.
Shouldn’t have defs

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/TextColor.svg
> +    <path fill="#000" d="M17.9488,5.078 L18.7958,6.376 C19.2268,7.036 22.9998,12.947 22.9998,16 C22.9998,18.059 21.4358,21 17.9578,21 C14.3458,21 12.9998,17.917 12.9998,16 C12.9998,12.952 16.6938,7.0
Should bit have full color and other attributes

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/TextColor.svg
> +  <defs>
Shouldn’t have defs

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'WarningeCircleBold', '18': 'WarningCircleBoldSmall',},
WarningCircle, not Warninge

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': '',
Redundant

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': '',
Redundant

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextRTLDecreas',
Typo

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'TextRTLDecreas'}
Typo

2021-05-06 19:32 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'ChevronUpSmall',
If I remember correctly, the idea was to give the title generic - for example ChevronUp, while both the regular and small variations should go inside the sizes object. Can you please check how it’s done in the wix style react one?

2021-05-09 07:35 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/DismissBold.svg
> +    <path id="dismissbold-a" d="M13.4135707,12.0003772 L16.7066965,8.70752558 C17.0977678,8.31729149 17.0977678,7.68366398 16.7066965,7.29342989 C16.3166408,6.90219004 15.6838162,6.90219004 15.292744
@shlomitc Weird svgo is suppose to get rid of defs... i'll remove by hand but i guess i should check them from now on.

2021-05-09 08:26 UTC, shlomitc requested changes
There are a few more broken svgs (paths, ids, etc...)
Also - please sign your commits

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/ConfirmBold.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24">
still broken

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/PlayCircle.svg
>      <path id="playcircle-a" d="M10.5,11.234 L12.849,12.5 L10.5,13.843 L10.5,11.234 Z M9.5,15.5 L14.5,12.5 L9.5,9.5 L9.5,15.5 Z M5,12.5 C5,8.916 7.916,6 11.5,6 C15.084,6 18,8.916 18,12.5 C18,16.084 15
this is still broken

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/TextMultilineBold.svg
>      <path id="textmultilinebold-a" d="M16,5 C17.657,5 19,6.343 19,8 L19,10 L17,10 L17,8 C17,7.447 16.553,7 16,7 L13,7 L13,16 L15,16 L15,18 L9,18 L9,16 L11,16 L11,7 L8,7 C7.447,7 7,7.447 7,8 L7,10 L5,
still broken

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/system/raw/BackToTop.svg
>      <path id="backtotop-a" d="M20.673,18.27 C20.481,18.424 20.24,18.5 20,18.5 C19.729,18.5 19.457,18.403 19.26,18.21 L16.582,15.597 L13.72,18.229 C13.336,18.582 12.703,18.592 12.306,18.251 C11.908,17
still broken

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/system/raw/MovetoFront.svg
>      <path id="movetofront-a" d="M17,19 L13,19 C11.89,19 11,18.104 11,17 L11,16 L10,16 C8.89,16 8,15.105 8,14 L8,13 L7,13 C5.89,13 5,12.105 5,11 L5,7 C5,5.895 5.89,5 7,5 L11,5 C12.1,5 13,5.895 13,7 L1
still broken

2021-05-09 08:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/general/raw/AddSmall.svg
> +    <polygon points="10 9 10 5 9 5 9 9 5 9 5 10 9 10 9 14 10 14 10 10 14 10 14 9"/>
broken

2021-05-09 08:51 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/general/raw/AddSmall.svg
> +    <polygon points="10 9 10 5 9 5 9 9 5 9 5 10 9 10 9 14 10 14 10 10 14 10 14 9"/>
That's not baseui icons i think because it's not in "classic-editor" folder, however i didn't see defs in this file.
![image](https://user-images.githubusercontent.com/46131591/117565993-d93e2180-b0bc-11eb-9888-e649905c2d54.png)

2021-05-09 09:05 UTC, shlomitc commented on packages/wix-ui-icons-common/src/general/raw/AddSmall.svg
> +    <polygon points="10 9 10 5 9 5 9 9 5 9 5 10 9 10 9 14 10 14 10 10 14 10 14 9"/>
I see. thanks

2021-05-09 10:22 UTC, shlomitc requested changes

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/Dashooard.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
typo - should be `Dashboard`

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'SelectedCircleSmall',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'DismissCircleBold',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'CloseButton',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'WixChat',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'ChevronUp', '18': 'ChevronUpSmall'}
small size is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'ChevronDown', '18': 'ChevronDownSmall'}
small size is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'ChevronRight', '18': 'ChevronRightSmall'}
small size is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'sizes': {'24': 'ChevronLeft', '18': 'ChevronLeftSmall'}
small size is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextRTL',
icon is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextLTR',
icon is missing

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextLTRIncrease',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextRTLIncrease',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextRTLDecrease',
missing icon

2021-05-09 10:22 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'TextLTRDecrease',
missing icon

2021-05-09 21:23 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/ConfirmCircleSmall.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
is this small?

2021-05-09 21:24 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/DismissBold.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24">
is this dismissBold or dismissCircleBold?

2021-05-09 21:25 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/FullWidthStrip.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
missing definition

2021-05-09 21:25 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/FullWidthStripBold.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
missing definition

2021-05-09 21:26 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/InfoSmall.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18" height="18" viewBox="0 0 18 18">
missing definition

2021-05-09 21:28 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/PremiumCircleBoldSmall.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
missing definition

2021-05-09 21:28 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/SelectedSmall.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
missing definition

2021-05-09 21:28 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/SiteTools.svg
>  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
missing definition

2021-05-09 21:29 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts
> +    'title': 'SocialBar',
already exists

2021-05-09 21:30 UTC, shlomitc commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/WarningBold.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
need to remove also from the definition

2021-05-10 06:10 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/classic-editor/general/raw/TextColor.svg
> +    <path fill="#000" d="M17.9488,5.078 L18.7958,6.376 C19.2268,7.036 22.9998,12.947 22.9998,16 C22.9998,18.059 21.4358,21 17.9578,21 C14.3458,21 12.9998,17.917 12.9998,16 C12.9998,12.952 16.6938,7.0
@shlomitc no, but this icon is unique because the tear drop element is used as a color picker.

2021-05-10 07:45 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-icons-common -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-icons-common**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-icons-common.pr_2101/

2021-05-10 08:20 UTC, merged