[wix-ui-icons-common] - Add tpa icons
wix/wix-ui pull request #2102
Opened 2021-05-06 08:46 UTC by bamai

2021-05-06 09:25 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-icons-common -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-icons-common**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-icons-common.pr_2102/

2021-05-11 10:42 UTC, mosheKerbel commented on packages/wix-ui-icons-common/stories/wix-ui-tpa/WixUiTpaCategoryList.st.css
> +.tableList th:nth-child(3),
@bamai see if you can use odd even selectors instead of this long list
[example](https://codepen.io/moshe_kerbel/pen/BaWoYym)

2021-05-11 11:44 UTC, shlomitc requested changes
1. Icons should be created according to the guidelines: https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common#guidelines. Please make sure the Icon creator exports it in the correct manner (see how the WSR icons svg look like)

2. expose the storey page here so it can be later consumed by the wix-ui-tpa storybook

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/raw/Admin.svg
> +</svg>
remove all ids
remove the `title`

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/raw/AdminFill.svg
> +    <g id="AdminFill_Medium_24X24" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" transform="translate(1.000000, 0.000000)">
is transform needed?

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/raw/AdminFill.svg
> +<svg width="25px" height="24px" viewBox="0 0 25 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
why 25px? shouldn't it be 24?

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/raw/AdminFillSmall.svg
> +<svg width="21px" height="20px" viewBox="0 0 21 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
why 21?

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/raw/ArrowLeftXLarge.svg
> +        <polygon id="Fill-2" fill="#000000" transform="translate(28.646500, 30.000000) scale(-1, 1) translate(-28.646500, -30.000000) " points="40.293 54 16.293 30 40.293 6 41 6.707 17.707 30 41 53.2
remove fill, probably all `transform` values are not needed

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/wix-ui-tpa/WixUiTpaCategoryList.st.css
> +.tableList table {
making this custom css is wrong. ALL related CSS should come from `wix-storybook-utils` components

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/types.ts
> + export type TpaTableRow = [
if it's not shared anywhere besides in your table, then I don't think it should be in this common file

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/src/wix-ui-tpa/metadata.ts
> +    sizes: {"12":"CloseXXSmall", "16":"CloseXSmall", "20":"CloseSmall", "24":"Close", "30":"CloseLarge" },
as we discussed - we need to understand if all sizes should actually exist in our design system

2021-05-11 11:44 UTC, shlomitc commented on packages/wix-ui-icons-common/.gitignore
> +/wix-ui-tpa
on-stage

2021-05-18 14:17 UTC, bamai commented on packages/wix-ui-icons-common/stories/wix-ui-tpa/WixUiTpaCategoryList.st.css
> +.tableList table {
This is how other libraries implemented the tables, otherwise the width of the columns is not consistent between tables:
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-icons-common/stories/components/general-category-list-base/GeneralCategoryListBase.st.css
Do you think we should remove the css there too? Or should we use the same css that is used there?

2021-05-19 06:42 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/general-category-list-base/GeneralCategoryListBase.tsx
> +  const smallIconTitle = smallIconSize===20? "12" : "18";
This should be better refactored.
You did create a more generic component but now it knows about a certain constrain which isn't generic.
if `20` is a concern of the on-stage, it should stay there.

It's good that the component will have some default sizes (18 and 24) and have a prop to change those. the prop should contain the new size and the names, regardless of what was there before. some kind of a map 
```js
{
  small: 20,
  medium: 24
}
```

so instead of `smallSize` I think it's better to call it `iconsSizes`

2021-05-19 06:42 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/wix-ui-tpa/WixUiTpaCategoryList.st.css
> +.tableList table {
I see. so let's finish this PR like that and consider refactoring afterwards

2021-05-19 08:55 UTC, shlomitc commented on packages/wix-ui-icons-common/stories/components/general-category-list-base/GeneralCategoryListBase.tsx
> +    smallSize: 18,
This can be a key-value map
small: 18
medium: 24

2021-05-25 16:07 UTC, jonathanadler approved these changes
Nice work!

Did you make sure it's creating the correct package (in `npm pack`)?
Let's work on merging this tomorrow.
This means we need to accept the visual test diffs again, run it again and then merge 💪

2021-05-26 12:29 UTC, merged