Naver & Loyalty | New Icons
wix/wix-ui pull request #2107
Opened 2021-05-14 13:42 UTC by ZilvinasMaciulis

2021-05-17 08:12 UTC, Zivilekin commented on packages/wix-ui-icons-common/src/general/metadata.ts
> +	 },
Could you align this block of code to the left?

2021-05-17 08:13 UTC, Zivilekin commented on packages/wix-ui-icons-common/src/general/metadata.ts
> +	 },
And this also align to the left

2021-05-19 10:17 UTC, ZilvinasMaciulis commented on packages/wix-ui-icons-common/src/general/metadata.ts
> +	 },
@Zivilekin done

2021-05-19 10:17 UTC, ZilvinasMaciulis commented on packages/wix-ui-icons-common/src/general/metadata.ts
> +	 },
@Zivilekin Done

2021-05-19 12:02 UTC, Zivilekin approved these changes

2021-05-19 12:42 UTC, Zivilekin requested changes

2021-05-19 12:42 UTC, Zivilekin commented on packages/wix-ui-icons-common/src/general/metadata.ts
> +  sizes: { "18": "LoyaltySmall”, "24": "Loyalty" },
```suggestion
  sizes: { "18": "LoyaltySmall", "24": "Loyalty" },
```

2021-05-24 12:17 UTC, Zivilekin approved these changes

2021-05-24 12:21 UTC, merged

2021-05-24 12:48 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-icons-common -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-icons-common**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-icons-common.pr_2107/