expose AnchorTitled component
wix/wix-ui pull request #2133
Opened 2021-06-29 08:12 UTC by TalZa1810

Expose AnchorTitled component so it can be used within the cheatsheet

2021-06-29 11:44 UTC, TalZa1810 commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +            onClick={!isChildren ? onCopy : null}
this was changed

2021-06-29 11:44 UTC, TalZa1810 commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +            { isChildren ?
this was changed

2021-06-29 11:55 UTC, TalZa1810 commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +    const onAnchorClicked = event => isChildren? onCopy(event): event.preventDefault();
adding a check here `isChildren`

2021-06-29 12:16 UTC, TalZa1810 commented
Hey @mykas,
I've added an example to the components section within storybook.
I wasn't sure whether I should add unit tests for this component.
Also, do I need to update types definitions? I saw this file but wasn't sure where should I update the types:
`packages/wix-storybook-utils/src/typings/story-section.ts`.


CC: @milkyfruit 
I just wanted to make sure, UX wise, that it's ok to use this component within the cheatsheet so that users can share a link to a specific example within the cheatsheet as well like we have with regular storybook examples.

2021-07-01 08:19 UTC, mykas requested changes

2021-07-01 08:19 UTC, mykas commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +            onClick={!isChildren ? onCopy : null}
```suggestion
            onClick={!isChildren && onCopy}
```

2021-07-01 08:20 UTC, mykas commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +export const AnchoredTitle = ({ title, children }) => {
I think you missed to update the place where this AnchoredTitle is used in Section folder.

2021-07-01 08:21 UTC, mykas commented on packages/wix-storybook-utils/src/AnchoredTitle/index.tsx
> +export const AnchoredTitle = ({ title, children }) => {
https://github.com/wix/wix-ui/blob/ef8346bb7aecef383e7ddd8582d5f44bc185a13b/packages/wix-storybook-utils/src/Sections/section-with-siblings/index.tsx#L11

2021-07-01 08:58 UTC, mykas commented
> packages/wix-storybook-utils/src/typings/

Typings there are for storybook sections so there is no need for that. Regarding unit tests this component did not have any, but it would be great if you could add some knowing that we have now another place that uses it.

2021-07-05 10:21 UTC, mykas approved these changes

2021-07-05 11:22 UTC, merged