Revert "Fix publish do revert (#2177)"
wix/wix-ui pull request #2178
Opened 2021-08-02 20:01 UTC by jonathanadler

This reverts commit b1655e4b9d9c486cf122711483c77fb670fce282.

So I had to remove Janet in order to get the master build work again.
I wasn't able to find an easier solution.

It seems that the release script is running without node_modules and without the build result, so both `build-storybook` and `npx build-storybook` didn't work in this stage.
We had a similar issue when we moved to the monorepo (@argshook should probably remember, cause I negged him a lot about it 😛 ).

So I created this PR to try and bring Janet back.
We'll probably need to do some changes with this script, maybe even talk to CI.

2021-08-02 20:26 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-core -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-core**

You can find it under one of the following URLs:
* https://wix-pages.com/wix-ui-core.pr_2178/

2021-08-03 08:34 UTC, argshook requested changes

2021-08-03 08:34 UTC, argshook commented on packages/wix-ui-core/package.json
> +    "release": "npx @wix/yoshi@4 release && npx build-storybook && npx janet deploy --ci",
```suggestion
    "release": "npx @wix/yoshi@4 release && npx build-storybook --package @storybook/react@5 && npx janet deploy --ci",
```

executing `npx build-storybook` would try to install `build-storybook`
package and run `build-storybook` from `node_modules/.bin`. But in this
case `build-storybook` is coming from `@storybook/react` package.

with `--package` flag we can set which package to get this binary from.

2021-08-03 08:36 UTC, argshook commented
we might need to add `npm install` to `release` script, cause i'm not sure if only `build-storybook` will be enough

2021-08-03 09:52 UTC, jonathanadler commented on packages/wix-ui-core/package.json
> +    "release": "npx @wix/yoshi@4 release && npx build-storybook && npx janet deploy --ci",
Nice!

It's true, cause I tried it with `npx build-storybook` and it failed with
`npm ERR! 404 Not Found - GET http://npm.dev.wixpress.com/build-storybook - not_found`

2021-08-03 09:54 UTC, jonathanadler commented
> we might need to add `npm install` to `release` script, cause i'm not sure if only `build-storybook` will be enough

@argshook `npm install` and `npm build` as well?

If I'm not mistaken, the release process does come with the `dist` folder, right?
Maybe we can have a storybook configuration that uses the `dist` components?
And then we won't need to `npm install` and `npm build`?

2021-11-15 09:16 UTC, closed without merging