Relaced old icons with newer version and updated two icon names
wix/wix-ui pull request #2280
Opened 2021-11-09 14:26 UTC by Zohar-Telor

Replaced "AppMarketNew" & "BlogNew" with AppMarket" & "Blog", updated all left menu icons to be 30px and updated all the icons to the new versions.

2021-11-09 14:58 UTC, env-github-token commented
<!-- PRֹֹֹ_COMMENT_FOR:wix-ui-icons-common -->

### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-icons-common**
Commit: **714395174977924091d176db662abe1e0dc89594**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-icons-common.pr_2280/

2021-11-10 12:58 UTC, TalZa1810 requested changes
Please review my comments. 
Also, please let's split this to multiple PRs because it makes this harder to track and make sure we don't break anyone when there are too many files.
Thanks 🙏

2021-11-10 12:58 UTC, TalZa1810 commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    title: 'Blog',
this means renaming the component. This could break existing users so we can't do this.

2021-11-10 12:58 UTC, TalZa1810 commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    title: 'AppMarket',
this could break existing users so we can't do this.

2021-11-10 12:58 UTC, TalZa1810 commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    sizes: { "30": "Elements" },
I dont see a change with this file. it's not in the PR.

2021-11-14 15:27 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    title: 'Blog',
@TalZa1810 Can you check if someone is using it? because this icon is for a very specific use-case which was not using baseui.
They are now starting to replace the existing icons there, so better change the name before.

2021-11-14 15:27 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    title: 'AppMarket',
@TalZa1810 Same thing.

2021-11-14 15:31 UTC, Zohar-Telor commented on packages/wix-ui-icons-common/src/classic-editor/system/metadata.ts
> +    sizes: { "30": "Elements" },
Should be 26, like all the other icons in it's category, but yes it's not related to this PR, i guess it's something i changed back when uploaded it and didn't push?

2021-11-14 15:33 UTC, Zohar-Telor commented
I actually asked the guys in the office if it would be better to split it into different PRs or to a big one and was told to do one because it's easier to review :\

2022-05-22 09:52 UTC, closed without merging