wix-ui-tpa types migration codemod
wix/wix-ui pull request #2299
Opened 2021-12-05 08:55 UTC by jonathanadler

2021-12-05 10:09 UTC, shlomitc requested changes

2021-12-05 10:09 UTC, shlomitc commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.output.js
> +import { ScrollableTabsScrollPosition, TabsSkin, TabsAlignment, TabsVariant, TabsNavButtonOptions } from 'wix-ui-tpa/Tabs';
Aren't we removing the entry-per-component in v3?
shouldn't it be importing it from `wix-ui-tpa/types.ts` instead?

2021-12-05 10:46 UTC, jonathanadler commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.output.js
> +import { ScrollableTabsScrollPosition, TabsSkin, TabsAlignment, TabsVariant, TabsNavButtonOptions } from 'wix-ui-tpa/Tabs';
You can't import from the index file without running this codemod first, because you're going to get name collisions.
So this codemod will have to be run before moving to the index file

2021-12-05 10:52 UTC, shlomitc commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.output.js
> +import { ScrollableTabsScrollPosition, TabsSkin, TabsAlignment, TabsVariant, TabsNavButtonOptions } from 'wix-ui-tpa/Tabs';
And then another codemod will fix the import to the root?

2021-12-05 11:00 UTC, jonathanadler commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.output.js
> +import { ScrollableTabsScrollPosition, TabsSkin, TabsAlignment, TabsVariant, TabsNavButtonOptions } from 'wix-ui-tpa/Tabs';
Exactly.
This one: https://github.com/wix/wix-ui/blob/master/packages/wix-ui-codemod/src/wix-ui-tpa/import-components-via-index-file.ts

2021-12-05 14:21 UTC, sivanharel approved these changes
Look awesome!

2021-12-05 14:41 UTC, nitayneeman reviewed
Looks good!

2021-12-05 14:41 UTC, nitayneeman commented on packages/wix-ui-codemod/src/wix-ui-tpa/types-rename-migration/old-types-to-new-map.ts
> +    Placement: 'popoverPlacementType',
According to the types map doc it should be `PopoverPlacement` 🤔

2021-12-05 14:41 UTC, nitayneeman commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.input.js
> +console.log('yo');
```suggestion
```

2021-12-05 14:41 UTC, nitayneeman commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.output.js
> +console.log('yo');
```suggestion
```

2021-12-05 14:41 UTC, nitayneeman commented on packages/wix-ui-codemod/src/wix-ui-tpa/types-rename-migration/index.ts
> +const renameTypes: Transform = (fileInfo, api) => {
So the V3 codemod is going to use this function right?
Currently it's not being used?

2021-12-05 14:54 UTC, sivanharel commented on packages/wix-ui-codemod/src/wix-ui-tpa/types-rename-migration/index.ts
> +const renameTypes: Transform = (fileInfo, api) => {
We could run it by running this command from a project: `npx wix-ui-codemod wix-ui-tpa/types-rename-migration/ ./`
But yes, this would be executed also from the `migrate-wut3` codemod which is currently in dev :)

2021-12-05 15:16 UTC, jonathanadler commented on packages/wix-ui-codemod/src/wix-ui-tpa/types-rename-migration/old-types-to-new-map.ts
> +    Placement: 'popoverPlacementType',
That's true!

2021-12-05 15:18 UTC, jonathanadler commented on packages/wix-ui-codemod/src/wix-ui-tpa/__testfixtures__/types-rename-migration.input.js
> +console.log('yo');
yeah all the tests in this library have this line, I'm not sure why 😄

2021-12-05 19:38 UTC, shlomitc approved these changes

2021-12-06 07:04 UTC, nitayneeman approved these changes

2021-12-06 08:30 UTC, merged